export default {
  'en-US': 'English, US',
  'en-AU': 'English, Australia',
  'en-CA': 'English, Canada',
  'en-IN': 'English, India',
  'en-NZ': 'English, New Zealand',
  'en-ZA': 'English, S. Africa',
  'en-GB': 'English, UK',
  'cmn-Hans-CN': '普通话 (中国大陆)',
  'cmn-Hant-TW': '中文 (台灣)',
  'yue-Hant-HK': '粵語 (香港)',
  'ja-JP': '日本語',
  'id-ID': 'Bahasa, Indonesia',
  'ms-MY': 'Bahasa, Melayu',
  'bg-BG': 'Bulgarian',
  'cs-CZ': 'Czech',
  'de-DE': 'Deutsch',
  'nl-NL': 'Dutch, Netherlands',
  'es-AR': 'español, Argentina',
  'es-BO': 'español, Bolivia',
  'es-CL': 'español, Chile',
  'es-CO': 'español, Colombia',
  'es-CR': 'español, Costa Rica',
  'es-EC': 'español, Ecuador',
  'es-SV': 'español, El Salvador',
  'es-ES': 'español, España',
  'es-US': 'español, Estados Unidos',
  'es-GT': 'español, Guatemala',
  'es-HN': 'español, Honduras',
  'es-MX': 'español, México',
  'es-NI': 'español, Nicaragua',
  'es-PA': 'español, Panamá',
  'es-PY': 'español, Paraguay',
  'es-PE': 'español, Perú',
  'es-PR': 'español, Puerto Rico',
  'es-DO': 'español, R. Dominicana',
  'es-UY': 'español, Uruguay',
  'es-VE': 'español, Venezuela',
  'fr-FR': 'français',
  'is-IS': 'Icelandic',
  'zu-ZA': 'IsiZulu',
  'it-IT': 'italiano',
  'it-CH': 'italiano, Svizzera',
  'ko-KR': 'Korean',
  'hu-HU': 'Magyar',
  'nb-NO': 'Norwegian',
  'pl-PL': 'Polski',
  'pt-BR': 'Português, Brasil',
  'pt-PT': 'Português, Portugal',
  'ro-RO': 'română',
  'ru-RU': 'России',
  'sr-RS': 'Serbian',
  'sk-SK': 'Slovak',
  'fi-FI': 'Suomi',
  'sv-SE': 'Svenska',
  'tr-TR': 'Turkish',
  'el-GR': 'Ελληνικά',
  'he-IL': 'עברית',
  'ar-DZ': 'العربية, Algeria',
  'ar-EG': 'العربية, Egypt',
  'ar-IQ': 'العربية, Iraq',
  'ar-JO': 'العربية, Jordan',
  'ar-KW': 'العربية, Kuwait',
  'ar-LB': 'العربية, Lebanon',
  'ar-MA': 'العربية, Morocco',
  'ar-QA': 'العربية, Qatar',
  'ar-SA': 'العربية, Saudi Arabia',
  'ar-AE': 'العربية, UAE',
}
